# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.omnibus.chef_version = :latest
  config.vm.box = 'opscode-ubuntu-14.04'
  config.vm.network "private_network", ip: '192.168.33.10'
  config.vm.synced_folder '../', '/srv/src'
end
