# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.omnibus.chef_version = :latest
  config.vm.box = 'opscode-ubuntu-14.04'
  config.vm.network "private_network", ip: '192.168.33.10'
  config.vm.synced_folder '../', '/srv/src'

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["./chef-repo/cookbooks", "./chef-repo/site-cookbooks"]
    chef.add_recipe 'npm'
  end
end
